-- Crear la base de datos si no existe con codificación UTF-8
CREATE DATABASE IF NOT EXISTS quiz_game_database
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;

USE quiz_game_database;

-- Tabla de Usuarios
CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL  
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Tabla de Dificultad
CREATE TABLE IF NOT EXISTS difficulty (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Tabla de Preguntas
CREATE TABLE IF NOT EXISTS question (
    id INT AUTO_INCREMENT PRIMARY KEY,  
    description TEXT NOT NULL,
    difficulty_id INT, 
    FOREIGN KEY (difficulty_id) REFERENCES difficulty(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Tabla de Respuestas
CREATE TABLE IF NOT EXISTS answer (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_id INT,
    description VARCHAR(255) NOT NULL,
    correct BOOLEAN NOT NULL,
    FOREIGN KEY (question_id) REFERENCES question(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- Tabla de Puntuaciones
CREATE TABLE IF NOT EXISTS score (
    id INT AUTO_INCREMENT PRIMARY KEY,  
    user_id INT, 
    score INT NOT NULL,
    win BOOLEAN NOT NULL,
    difficulty_id INT,  
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (difficulty_id) REFERENCES difficulty(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;


-- Insertar datos de dificultad
INSERT INTO difficulty (name) VALUES 
('easy'), 
('medium'), 
('hard');

-- Preguntas fáciles
INSERT INTO question (description, difficulty_id) VALUES 
('CUAL ES LA CAPITAL DE FRANCIA', 1),
('QUE ES LA FOTOSINTESIS', 1),
('CUANTOS CONTINENTES HAY EN EL MUNDO', 1),
('CUAL ES EL OCEANO MAS GRANDE', 1),
('QUE ANIMAL ES CONOCIDO COMO EL REY DE LA SELVA', 1),
('CUAL ES EL COLOR DEL CIELO EN UN DIA DESPEJADO', 1),
('QUIEN ESCRIBIO CIEN ANOS DE SOLEDAD', 1),
('QUE INSTRUMENTO MUSICAL TIENE CUERDAS Y SE TOCA CON UN ARCO', 1),
('CUANTAS PATAS TIENE UN PERRO', 1),
('QUE PLANETA ES CONOCIDO COMO EL PLANETA ROJO', 1),
('CUAL ES EL IDIOMA MAS HABLADO EN EL MUNDO', 1),
('QUE FRUTA ES AMARILLA Y SE PELA', 1),
('QUE PARTE DEL CUERPO USAMOS PARA OIR', 1),
('QUE MES SIGUE A ENERO', 1),
('EN QUE CONTINENTE SE ENCUENTRA EGIPTO', 1);

-- PREGUNTAS MEDIAS
INSERT INTO question (description, difficulty_id) VALUES 
('QUIEN PINTO LA MONA LISA', 2),
('QUE ES EL ADN', 2),
('CUAL ES LA CAPITAL DE JAPON', 2),
('QUE EVENTO HISTORICO OCURRIO EN 1492', 2),
('CUAL ES EL SISTEMA POLITICO DE LOS ESTADOS UNIDOS', 2),
('QUIEN ES EL AUTOR DE DON QUIJOTE DE LA MANCHA', 2),
('CUAL ES EL PAIS MAS GRANDE DEL MUNDO', 2),
('QUE ES LA FOTOSINTESIS', 2),
('CUAL ES EL RIO MAS LARGO DEL MUNDO', 2),
('QUIEN FUE ALBERT EINSTEIN', 2),
('CUAL ES LA FORMULA DEL AGUA', 2),
('QUE ES LA REVOLUCION INDUSTRIAL', 2),
('QUIEN FUE EL PRIMER HOMBRE EN LA LUNA', 2),
('QUE ES EL CAMBIO CLIMATICO', 2),
('QUIEN ESCRIBIO ROMEO Y JULIETA', 2);

-- PREGUNTAS DIFICILES
INSERT INTO question (description, difficulty_id) VALUES 
('QUE TEORIA EXPLICA LA FORMACION DEL UNIVERSO', 3),
('QUIEN DESARROLLO LA TEORIA DE LA RELATIVIDAD', 3),
('QUE ES LA CUANTICA', 3),
('CUAL ES LA OBRA MAS FAMOSA DE SHAKESPEARE', 3),
('QUE ES UN AGUJERO NEGRO', 3),
('QUIEN FUE EL PRIMER EMPERADOR ROMANO', 3),
('QUE ES EL BIG BANG', 3),
('QUE CIVILIZACION CONSTRUYO LAS PIRAMIDES DE EGIPTO', 3),
('CUAL ES EL LENGUAJE DE PROGRAMACION MAS UTILIZADO', 3),
('QUE ES EL TEOREMA DE PITAGORAS', 3),
('QUIEN PROPUSO LA TEORIA DE LA EVOLUCION', 3),
('QUE ES LA INTELIGENCIA ARTIFICIAL', 3),
('QUE SIGNIFICA FILOSOFIA', 3),
('QUE ES LA BIOETICA', 3),
('CUAL ES LA DIFERENCIA ENTRE UN VIRUS Y UNA BACTERIA', 3);

-- RESPUESTAS PARA PREGUNTAS FACILES
INSERT INTO answer (question_id, description, correct) VALUES 
(1, 'PARIS', TRUE), 
(1, 'LONDRES', FALSE), 
(1, 'BERLIN', FALSE), 

(2, 'EL PROCESO POR EL CUAL LAS PLANTAS PRODUCEN ENERGIA', TRUE), 
(2, 'UN TIPO DE BEBIDA', FALSE), 
(2, 'UNA ENFERMEDAD', FALSE), 

(3, 'SIETE', FALSE), 
(3, 'SEIS', FALSE), 
(3, 'CINCO', TRUE), 

(4, 'OCEANO ATLANTICO', FALSE), 
(4, 'OCEANO PACIFICO', TRUE), 
(4, 'OCEANO INDICO', FALSE), 

(5, 'ELEFANTE', FALSE), 
(5, 'LEON', TRUE), 
(5, 'TIGRE', FALSE), 

(6, 'AZUL', TRUE), 
(6, 'VERDE', FALSE), 
(6, 'ROJO', FALSE), 

(7, 'GABRIEL GARCIA MARQUEZ', TRUE), 
(7, 'JULIO CORTAZAR', FALSE), 
(7, 'JORGE LUIS BORGES', FALSE), 

(8, 'PIANO', FALSE), 
(8, 'GUITARRA', TRUE), 
(8, 'BATERIA', FALSE), 

(9, 'CUATRO', TRUE), 
(9, 'TRES', FALSE), 
(9, 'DOS', FALSE), 

(10, 'MARTE', TRUE), 
(10, 'JUPITER', FALSE), 
(10, 'TIERRA', FALSE), 

(11, 'CHINO', FALSE), 
(11, 'ESPANOL', FALSE), 
(11, 'INGLES', TRUE), 

(12, 'PLATANO', TRUE), 
(12, 'MANZANA', FALSE), 
(12, 'NARANJA', FALSE), 

(13, 'OIDO', TRUE), 
(13, 'OJO', FALSE), 
(13, 'NARIZ', FALSE), 

(14, 'FEBRERO', TRUE), 
(14, 'MARZO', FALSE), 
(14, 'ENERO', FALSE), 

(15, 'AFRICA', TRUE), 
(15, 'ASIA', FALSE), 
(15, 'EUROPA', FALSE); 

-- RESPUESTAS PARA PREGUNTAS MEDIAS
INSERT INTO answer (question_id, description, correct) VALUES 
(16, 'LEONARDO DA VINCI', TRUE), 
(16, 'PABLO PICASSO', FALSE), 
(16, 'VINCENT VAN GOGH', FALSE), 

(17, 'UN MATERIAL GENETICO', TRUE), 
(17, 'UNA ENFERMEDAD', FALSE), 
(17, 'UN TIPO DE CELULA', FALSE), 

(18, 'TOKIO', TRUE), 
(18, 'PEKIN', FALSE), 
(18, 'SEUL', FALSE), 

(19, 'LA LLEGADA DE CRISTOBAL COLON A AMERICA', TRUE), 
(19, 'LA CAIDA DEL MURO DE BERLIN', FALSE), 
(19, 'LA PRIMERA GUERRA MUNDIAL', FALSE), 

(20, 'DEMOCRACIA', TRUE), 
(20, 'MONARQUIA', FALSE), 
(20, 'DICTADURA', FALSE), 

(21, 'MIGUEL DE CERVANTES', TRUE), 
(21, 'GABRIEL GARCIA MARQUEZ', FALSE), 
(21, 'JORGE LUIS BORGES', FALSE), 

(22, 'RUSIA', TRUE), 
(22, 'CANADA', FALSE), 
(22, 'CHINA', FALSE), 

(23, 'EL PROCESO POR EL CUAL LAS PLANTAS PRODUCEN ENERGIA', TRUE), 
(23, 'UN TIPO DE BEBIDA', FALSE), 
(23, 'UNA ENFERMEDAD', FALSE), 

(24, 'AMAZONAS', TRUE), 
(24, 'NILO', FALSE), 
(24, 'YANGTSE', FALSE), 

(25, 'UN FISICO', TRUE), 
(25, 'UN FILOSOFO', FALSE), 
(25, 'UN MEDICO', FALSE), 

(26, 'H2O', TRUE), 
(26, 'O2', FALSE), 
(26, 'CO2', FALSE), 

(27, 'EL CAMBIO DE LAS CONDICIONES DE VIDA EN LA INDUSTRIA', TRUE), 
(27, 'UN MOVIMIENTO POLITICO', FALSE), 
(27, 'UN CAMBIO CLIMATICO', FALSE), 

(28, 'NEIL ARMSTRONG', TRUE), 
(28, 'BUZZ ALDRIN', FALSE), 
(28, 'YURI GAGARIN', FALSE), 

(29, 'UN AUMENTO EN LAS TEMPERATURAS GLOBALES', TRUE), 
(29, 'UN CAMBIO DE GOBIERNO', FALSE), 
(29, 'UNA GUERRA', FALSE), 

(30, 'WILLIAM SHAKESPEARE', TRUE), 
(30, 'J K ROWLING', FALSE), 
(30, 'ERNEST HEMINGWAY', FALSE);

-- RESPUESTAS PARA PREGUNTAS DIFICILES
INSERT INTO answer (question_id, description, correct) VALUES 
(31, 'LA TEORIA DEL BIG BANG', TRUE),
(31, 'LA TEORIA DE CUERDAS', FALSE),
(31, 'LA TEORIA DEL TODO', FALSE),

(32, 'ALBERT EINSTEIN', TRUE),
(32, 'ISAAC NEWTON', FALSE),
(32, 'GALILEO GALILEI', FALSE),

(33, 'ESTUDIO DE PARTICULAS SUBATOMICAS', TRUE),
(33, 'ESTUDIO DE LA GRAVEDAD', FALSE),
(33, 'ESTUDIO DE LOS AGUJEROS NEGROS', FALSE),

(34, 'HAMLET', TRUE),
(34, 'MACBETH', FALSE),
(34, 'OTELO', FALSE),

(35, 'UN OBJETO CON GRAVEDAD TAN INTENSA QUE NADA PUEDE ESCAPAR', TRUE),
(35, 'UNA ESTRELLA ENANA', FALSE),
(35, 'UN TIPO DE MATERIA OSCURA', FALSE),

(36, 'AUGUSTO', TRUE),
(36, 'NERON', FALSE),
(36, 'JULIO CESAR', FALSE),

(37, 'LA EXPLOSION INICIAL DEL UNIVERSO', TRUE),
(37, 'UN TIPO DE ESTRELLA', FALSE),
(37, 'UNA TEORIA DE GRAVEDAD', FALSE),

(38, 'LOS EGIPCIOS', TRUE),
(38, 'LOS ROMANOS', FALSE),
(38, 'LOS GRIEGOS', FALSE),

(39, 'JAVASCRIPT', TRUE),
(39, 'PYTHON', FALSE),
(39, 'C SHARP', FALSE),

(40, 'UNA RELACION ENTRE LOS LADOS DE UN TRIANGULO', TRUE),
(40, 'UNA FORMULA MATEMATICA', FALSE),
(40, 'UN PRINCIPIO DE LA FISICA', FALSE),

(41, 'CHARLES DARWIN', TRUE),
(41, 'LOUIS PASTEUR', FALSE),
(41, 'GREGOR MENDEL', FALSE),

(42, 'EL ESTUDIO DE LA EXISTENCIA', TRUE),
(42, 'EL ESTUDIO DE LA MENTE', FALSE),
(42, 'EL ESTUDIO DE LA NATURALEZA', FALSE),

(43, 'ETICA EN LA BIOMEDICINA', TRUE),
(43, 'EL ESTUDIO DE LA BIOLOGIA', FALSE),
(43, 'ETICA EN LA INVESTIGACION', FALSE),

(44, 'LOS VIRUS SON MAS PEQUENOS QUE LAS BACTERIAS', TRUE),
(44, 'AMBOS SON IGUALES', FALSE),
(44, 'LAS BACTERIAS SON MAS PELIGROSAS', FALSE);
